import React, { useEffect, useState } from 'react';
import { AlertTriangle, RefreshCw, CircleAlert, TrendingUp } from 'lucide-react';
import { apiService, RealCloudSummary } from '@/services/apiService';

export default function PredictionPage() {
  const [data, setData] = useState<RealCloudSummary | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { setData(await apiService.getRealCloudSummary()); setError(null); } catch (e) { setError(e instanceof Error ? e.message : 'Could not retrieve live telemetry'); setData(null); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-slate-100"><AlertTriangle className="text-amber-400"/> Failure Prediction Engine</h1><p className="mt-1 text-sm text-slate-400">Short-horizon trend analysis calculated from actual provider telemetry.</p></div><button onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 bg-slate-800 px-3 py-2 text-sm text-slate-200 disabled:opacity-50"><RefreshCw size={15} className={loading ? 'animate-spin' : ''}/> Refresh</button></div>
    <div className="rounded-xl border border-amber-700/50 bg-amber-950/20 p-4 text-xs text-amber-100">These are trend-based warnings, not guarantees or calibrated ML confidence scores. The forecast uses recent live CPU/memory samples and a simple linear extrapolation. No prediction is generated when there are too few samples.</div>
    {loading && <div className="rounded-xl border border-slate-700 bg-slate-800/40 p-8 text-center text-slate-400">Analyzing real metric samples…</div>}
    {error && !loading && <div className="rounded-xl border border-rose-800 bg-rose-950/30 p-5 text-sm text-rose-200"><CircleAlert className="mb-2"/>{error}</div>}
    {data && !loading && <><p className="text-xs text-slate-500">Source: {data.source} · Observed at {new Date(data.observedAt).toLocaleString()}</p>{data.predictions.length === 0 ? <div className="rounded-xl border border-slate-700 bg-slate-800/40 p-8 text-center"><TrendingUp className="mx-auto mb-3 text-cyan-400"/><h2 className="font-semibold text-slate-100">No current trend alerts</h2><p className="mt-2 text-sm text-slate-400">Either the measured trends are below the alert threshold, or there are not yet enough historical samples. No synthetic alerts are displayed.</p></div> : <div className="grid grid-cols-1 gap-4 md:grid-cols-2">{data.predictions.map(p => <article key={p.id} className="rounded-xl border border-slate-700 bg-slate-800/60 p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold text-slate-100">{p.title}</h2><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${p.severity === 'HIGH' ? 'bg-rose-500/10 text-rose-300' : 'bg-amber-500/10 text-amber-300'}`}>{p.severity}</span></div><p className="mt-2 text-xs text-slate-400">Service ID: {p.serviceId}</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-lg bg-slate-900/60 p-3"><div className="text-xs text-slate-500">Current measured</div><div className="mt-1 text-xl font-bold text-slate-100">{p.currentPercent.toFixed(1)}%</div></div><div className="rounded-lg bg-slate-900/60 p-3"><div className="text-xs text-slate-500">15-min trend estimate</div><div className="mt-1 text-xl font-bold text-cyan-300">{p.forecast15MinPercent.toFixed(1)}%</div></div></div><p className="mt-4 text-sm text-slate-300">{p.description}</p><p className="mt-3 text-[10px] uppercase tracking-wider text-slate-500">{p.source} · Trend only, not a failure probability</p></article>)}</div>}</>}
  </div>;
}
